version: "3.6"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  postgres:
    image: postgres:11-alpine
    container_name: mpulse-challenge-db
    depends_on:
      - kafka
      - zookeeper
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/src/postgresql/data
    env_file:
      - ./.env
    command: [ "postgres", "-c", "log_statement=all" ]
  python:
    depends_on:
      - postgres
      - kafka
      - zookeeper
    image: ubuntu:latest
    container_name: mpulse-challenge-env
    volumes:
      - ./:/usr/home/dev
    working_dir: /usr/home/dev
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    entrypoint: /usr/home/dev/scripts/entrypoint.sh
