version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: mpulse-challenge-db  
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/src/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=postgres
    command: ["postgres", "-c", "log_statement=all"]
